# Generated by Django 4.2.16 on 2024-12-24 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height', models.FloatField()),
                ('role', models.CharField(choices=[('common', 'Common User'), ('personal', 'Personal Trainer'), ('nutri', 'Nutritionist')], default='common', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('personal', models.ForeignKey(limit_choices_to={'role': 'personal'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_workout_plans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'common'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_workout_plans', to=settings.AUTH_USER_MODEL)),
                ('workouts', models.ManyToManyField(blank=True, related_name='workout_plans', to='core.workout')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('certificate', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('user', models.OneToOneField(limit_choices_to=models.Q(('role', 'personal'), ('role', 'nutri'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='specialist_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='online', max_length=20)),
                ('specialist', models.ForeignKey(limit_choices_to=models.Q(('role', 'personal'), ('role', 'nutri'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qtd', models.CharField(max_length=255)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.meal')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='core.workout')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('meals', models.ManyToManyField(blank=True, related_name='diet_plans', to='core.meal')),
                ('nutri', models.ForeignKey(limit_choices_to={'role': 'nutri'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_diet_plans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'common'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('canceled', 'Canceled'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20)),
                ('address_or_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('user_common', models.ForeignKey(limit_choices_to={'role': 'common'}, on_delete=django.db.models.deletion.CASCADE, related_name='common_appointments', to=settings.AUTH_USER_MODEL)),
                ('user_specialist', models.ForeignKey(limit_choices_to=models.Q(('role', 'personal'), ('role', 'nutri'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='specialist_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
