# Generated by Django 4.2.16 on 2024-11-21 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('user_common', models.ForeignKey(limit_choices_to={'role': 'common'}, on_delete=django.db.models.deletion.CASCADE, related_name='common_appointments', to=settings.AUTH_USER_MODEL)),
                ('user_specialist', models.ForeignKey(limit_choices_to=models.Q(('role', 'personal'), ('role', 'nutri'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='specialist_appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
