# Generated by Django 4.2.16 on 2024-11-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address_or_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('accepted', 'Accepted'), ('scheduled', 'Scheduled')], default='scheduled', max_length=20),
        ),
    ]
