# Generated by Django 4.2.16 on 2024-11-21 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_address_or_link_appointment_is_online_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.CharField(choices=[('online', 'Online'), ('in_person', 'In Person')], default='online', max_length=20)),
                ('specialist', models.ForeignKey(limit_choices_to=models.Q(('role', 'personal'), ('role', 'nutri'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
